### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by UQ-DongYuan** [JenAlchimowicz/Semantic-segmentation-with-PyTorch-Satellite-Imagery#1]
Hi there,

Thanks for your work. I'm just wondering where I can get the dataset for training and testing.

Cheers.

**Comment by rose-jinyang** [comment]
Hello
Thanks for contributing to this project.
Where can I get the dataset?
Thanks

**Comment by JenAlchimowicz** [comment]
Hi, the dataset originally comes from [Sagar Verma](https://sagarverma.github.io) and this [paper](https://sagarverma.github.io/qfabric)

You can dowload a copy of the dataset here: https://figshare.com/collections/semantic_segmentation_satellite_imagery/6026765

Thanks!
